In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the margin of words',
    'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the margin of words',
 'your videos are good']

In [21]:
### Defiine the voabulary sie

voc_size=10000

In [22]:
## One hot representation fro every word

one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[4030, 3479, 136, 3295],
 [4030, 3479, 136, 3503],
 [4030, 8599, 136, 5250],
 [2028, 2543, 6573, 503, 1457],
 [2028, 2543, 6573, 503, 9187],
 [5824, 4030, 1547, 136, 9070],
 [6002, 3012, 9585, 503]]

In [23]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
import numpy as np

In [28]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_doc

array([[   0,    0,    0,    0, 4030, 3479,  136, 3295],
       [   0,    0,    0,    0, 4030, 3479,  136, 3503],
       [   0,    0,    0,    0, 4030, 8599,  136, 5250],
       [   0,    0,    0, 2028, 2543, 6573,  503, 1457],
       [   0,    0,    0, 2028, 2543, 6573,  503, 9187],
       [   0,    0,    0, 5824, 4030, 1547,  136, 9070],
       [   0,    0,    0,    0, 6002, 3012, 9585,  503]])

In [29]:
### Feauture representation

dim = 10

In [32]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')



In [33]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [34]:
model.predict(embedded_doc)

1/1 [==============================] - 0s 125ms/step


array([[[-1.2717389e-02, -3.3126190e-02,  4.6912257e-02, -3.5116158e-02,
          5.9562549e-03, -1.1269879e-02,  3.6370803e-02, -2.3418618e-02,
         -5.4730400e-03,  2.3812439e-02],
        [-1.2717389e-02, -3.3126190e-02,  4.6912257e-02, -3.5116158e-02,
          5.9562549e-03, -1.1269879e-02,  3.6370803e-02, -2.3418618e-02,
         -5.4730400e-03,  2.3812439e-02],
        [-1.2717389e-02, -3.3126190e-02,  4.6912257e-02, -3.5116158e-02,
          5.9562549e-03, -1.1269879e-02,  3.6370803e-02, -2.3418618e-02,
         -5.4730400e-03,  2.3812439e-02],
        [-1.2717389e-02, -3.3126190e-02,  4.6912257e-02, -3.5116158e-02,
          5.9562549e-03, -1.1269879e-02,  3.6370803e-02, -2.3418618e-02,
         -5.4730400e-03,  2.3812439e-02],
        [ 3.7233535e-02,  2.0586979e-02,  2.1911014e-02,  5.0920732e-03,
          7.0963390e-03,  4.2109277e-02,  4.1467752e-02, -1.9538030e-03,
         -4.6437010e-03,  2.6226196e-02],
        [ 2.1808509e-02, -2.8896213e-02,  4.0772211e-02,  1.

In [35]:
embedded_doc[0]

array([   0,    0,    0,    0, 4030, 3479,  136, 3295])